stages:
  - build
  - test
  - staging
  - prod

build-job:
  stage: build
  script:
    - echo "build"

test-job:
  stage: test
  script:
    - echo "test"

staging-job:
  stage: staging
  script:
    - echo "staging"

deploy-job:
  stage: prod
  script:
    - echo "prod"