CREATE TABLE public.uers (
    idusers int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    usrename varchar NOT NULL,
    "password" varchar NOT NULL,
    CONSTRAINT users_pk PRIMARY KEY (idusers)
);

select * from pg_catalog.pg_tables where schemaname='public';