CREATE TABLE public.users (
    idusers int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username varchar NOT NULL,
    "password" varchar NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pk PRIMARY KEY (idusers)
);

select * from pg_catalog.pg_tables where schemaname='public';